FROM php:7.3-apache

RUN apt-get update \
    && apt-get upgrade \
    && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev libmcrypt-dev libicu-dev libxml2-dev libzip-dev zip \
    && docker-php-ext-configure zip --with-libzip \
    && docker-php-ext-install intl gd mbstring mysqli pdo_mysql soap zip

RUN pecl install mcrypt-1.0.2 && docker-php-ext-enable mcrypt